#!/bin/sh
set -eu

: "${HUB_TITLE:=Floodman Operations Hub}"
: "${HUB_RELEASE:=windows-business-suite-v3.0.0}"
: "${HUB_OFFICE_URL:=http://localhost:9000}"
: "${HUB_ROOMFLOW_URL:=https://theninjallo.github.io/roomflow/}"
: "${HUB_DOCUMENSO_URL:=http://localhost:9001}"
: "${HUB_MAILPIT_URL:=http://localhost:9002}"
: "${HUB_ENGINEERING_URL:=http://localhost:9003/lab}"
: "${HUB_API_URL:=http://localhost:9004/docs}"
: "${HUB_COMPETITOR_URL:=http://localhost:9000/office/intelligence}"
: "${HUB_SYNC_STATUS_URL:=http://localhost:9000/office/gauzy}"
: "${HUB_REMOTE_ACCESS_ENABLED:=false}"
: "${HUB_REMOTE_DOCUMENSO_PORT:=8443}"
: "${HUB_REMOTE_MAILPIT_PORT:=8444}"
: "${HUB_REMOTE_ENGINEERING_PORT:=8445}"
: "${HUB_REMOTE_API_PORT:=8446}"
: "${HUB_REMOTE_DOCUMENSO_URL:=}"
: "${HUB_REMOTE_MAILPIT_URL:=}"
: "${HUB_REMOTE_ENGINEERING_URL:=}"
: "${HUB_REMOTE_API_URL:=}"

export HUB_TITLE HUB_RELEASE HUB_OFFICE_URL HUB_ROOMFLOW_URL HUB_DOCUMENSO_URL \
  HUB_MAILPIT_URL HUB_ENGINEERING_URL HUB_API_URL HUB_COMPETITOR_URL HUB_SYNC_STATUS_URL \
  HUB_REMOTE_ACCESS_ENABLED HUB_REMOTE_DOCUMENSO_PORT HUB_REMOTE_MAILPIT_PORT \
  HUB_REMOTE_ENGINEERING_PORT HUB_REMOTE_API_PORT HUB_REMOTE_DOCUMENSO_URL \
  HUB_REMOTE_MAILPIT_URL HUB_REMOTE_ENGINEERING_URL HUB_REMOTE_API_URL

envsubst '${HUB_TITLE} ${HUB_RELEASE} ${HUB_OFFICE_URL} ${HUB_ROOMFLOW_URL} ${HUB_DOCUMENSO_URL} ${HUB_MAILPIT_URL} ${HUB_ENGINEERING_URL} ${HUB_API_URL} ${HUB_COMPETITOR_URL} ${HUB_SYNC_STATUS_URL} ${HUB_REMOTE_ACCESS_ENABLED} ${HUB_REMOTE_DOCUMENSO_PORT} ${HUB_REMOTE_MAILPIT_PORT} ${HUB_REMOTE_ENGINEERING_PORT} ${HUB_REMOTE_API_PORT} ${HUB_REMOTE_DOCUMENSO_URL} ${HUB_REMOTE_MAILPIT_URL} ${HUB_REMOTE_ENGINEERING_URL} ${HUB_REMOTE_API_URL}' \
  < /opt/floodman/hub-config.js.template \
  > /usr/share/nginx/html/floodman-hub-config.js

exec "$@"
