import type { Metadata } from "next";
import type { ReactNode } from "react";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import "./globals.css";

/**
 * Two families, both from the `geist` package, and nothing else.
 *
 * The previous version of this page loaded three: a variable editorial serif
 * for display, a grotesque for UI, and Geist Mono for figures. That was the
 * right call for a light editorial page and the wrong one for a developer tool
 * — a high-contrast serif at display size over a schema-migration product read
 * as a magazine cover about databases rather than as an instrument.
 *
 * `geist` self-hosts, which is the property that matters here: `next/font/google`
 * reaches out to fonts.googleapis.com at build time, and this app is built three
 * times in CI by the screenshot and verify harnesses, on runners where a cold
 * font fetch is one more thing that can fail for reasons unrelated to the page.
 *
 * Geist Mono is not decorative. It ships real tabular figures, and every number
 * on this page sits in a column that has to line up — see the `[data-metric]`
 * rule in `lib/tokens.ts`.
 *
 * Both `.variable` classes go on <html> so the CSS custom properties they define
 * are in scope for `app/globals.css`, which reads them through `@theme inline`.
 */
export const metadata: Metadata = {
  title: "Bellwether — rehearse the migration before it runs",
  description:
    "Replay a schema change against a slice of real production traffic, watch what it locks and for how long, and get a verdict before it touches the primary. A demo page generated by the frontend-design-pro skill pack.",
};

export interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en" className={`${GeistSans.variable} ${GeistMono.variable}`}>
      <body className="bg-surface-page text-ink antialiased">{children}</body>
    </html>
  );
}
